name: libmobility
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python <3.13
  - cmake >=3.24
  # - cuda-version 13.* # uncomment for a specific cuda version
  - gxx >9,<15
  - cuda-libraries-dev
  - cuda-nvcc 
  - make
  - blas-devel
  - libblas
  - liblapacke
  - numpy
  - pytest
  - scipy
  - pip
  - nanobind
  - pip:
    - sphinx==8.1.3
    - sphinx-rtd-theme==3.0.2
    - sphinxcontrib-autoprogram==0.1.9
    - sphinxcontrib-napoleon==0.7
    - gitpython
